[package]
name = "ggez-assets_manager"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[features]
default = ["ahash"]

ahash = ["assets_manager/ahash"]
hot-reloading = ["assets_manager/hot-reloading"]

[dependencies]
#assets_manager = {version = "0.7", default-features = false, features = ["parking_lot", "zip", "image"]}
assets_manager = {git = "https://github.com/a1phyr/assets_manager/", rev = "1948347", default-features = false, features = ["parking_lot", "zip", "image"]}
ggez = "0.7"

directories = "3.0"
image = {version = "0.23", default-features = false}
parking_lot = "0.11"

[dev-dependencies]
env_logger = "0.9"
log = "0.4"
